camera_bridge:
  ros__parameters:
    config:
      - ros_topic_name: "/camera/camera_info"
        gz_topic_name: "/camera/camera_info"
        ros_type_name: "sensor_msgs/msg/CameraInfo"
        gz_type_name: "gz.msgs.CameraInfo"
        direction: GZ_TO_ROS  # BIDIRECTIONAL or ROS_TO_GZ
      - ros_topic_name: "/camera/image"
        gz_topic_name: "/camera/image"
        ros_type_name: "sensor_msgs/msg/Image"
        gz_type_name: "gz.msgs.Image"
        direction: GZ_TO_ROS 
